{
  "data_processor": {
    "batch_size": 1000,
    "threads": 4,
    "max_memory": 2048,
    "log_level": "debug"
  },
  "input_data": {
    "data_source": "database",
    "db_host": "db.example.com",
    "db_port": 5432,
    "retry_attempts": 1005
  },
  "output_settings": {
    "output_format": "JSON",
    "output_path": "/data/output",
    "max_file_size": 1024
  }
}