{
  "network_settings": {
    "primary_dns": "8.8.8.8",
    "secondary_dns": "8.8.4.4",
    "max_sessions": 5,
    "session_timeout": 15
  },
  "vpn_settings": {
    "server_address": "vpn.corp.com",
    "port": 1194,
    "encryption_level": 256,
    "allow_split_tunneling": "false"
  },
  "access_groups": [
    "Admin",
    "User",
    "Guest"
  ],
  "security_policies": {
    "enforce_2fa": "true",
    "lockout_threshold": 10
  },
  "password_policy:": {
    "min_length": 12,
    "require_special": "true"
  }
}