{
  "server_config": {
    "server_name": "example.com",
    "listen_port": 80,
    "max_clients": 200,
    "timeout": 400,
    "enable_ssl": "true"
  },
  "ssl_config": {
    "cert_file": "/etc/ssl/certs/server.crt",
    "key_file": "/etc/ssl/private/server.key",
    "ssl_protocol": "TLSv1.2"
  },
  "cache_config": {
    "enabled": "true",
    "cache_size": 4096,
    "cache_timeout": 600
  }
}