{
  "network_settings": {
    "primary_dns": "8.8.8.8",
    "secondary_dns": "8.8.4.4",
    "max_sessions": 5,
    "session_timeout": 15
  },
  "vpn_settings": {
    "server_address": "vpn.corp.com",
    "port": 1194,
    "encryption_level": 256,
    "allow_split_tunneling": "false"
  },
  "access_groups": [
    "Admin",
    "User",
    "Guest"
  ],
  "security_policies": {
    "enforce_2fa": "true",
    "lockout_threshold": 10
  },
  "password_policy:": {
    "min_length": 12,
    "require_special": "true",
    "max_attempts": 20
  },
  "log_config": {
    "level": "info",
    "output_file": "/var/log/server.log",
    "max_size": 10240
  },
  "database_config": {
    "db_host": "db.example.com",
    "db_port": 5432,
    "username": "admin",
    "password": "password123",
    "max_pool_size": 50
  }
}